
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Manuel Jimeno
 */
public class Ventas extends javax.swing.JFrame {

    Connection conexion = null;
    String url = "jdbc:mysql://127.0.0.1:3306/proyectotortillas";
    String usuario = "root";
    String password = "";
    
    public Ventas() {
        initComponents();
        TextPrompt fecha = new TextPrompt("Fecha", txtFecha);
        TextPrompt monto = new TextPrompt("Monto", txtMonto);        
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProveedor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        txtFecha = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        comboFPago = new javax.swing.JComboBox<>();
        btnAgregarInv = new javax.swing.JButton();
        btnEliminarInv = new javax.swing.JButton();
        btnModificarInv = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        txtFecha.setToolTipText("Producto");

        comboFPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));

        btnAgregarInv.setText("Agregar");
        btnAgregarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarInvActionPerformed(evt);
            }
        });

        btnEliminarInv.setText("Eliminar");
        btnEliminarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInvActionPerformed(evt);
            }
        });

        btnModificarInv.setText("Modificar");
        btnModificarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarInvActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(comboFPago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnAgregarInv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarInv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarInv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarInv)
                    .addComponent(btnModificarInv)
                    .addComponent(btnAgregarInv)
                    .addComponent(btnRegresar))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInvActionPerformed
        String ventasSentencia = "null,'"+txtFecha.getText()+"',"+Float.parseFloat(txtMonto.getText())+",'"+comboFPago.getSelectedItem()+"'";
        String insertar = insertar("ventas", ventasSentencia);
        System.out.println(insertar);
        llenarTabla();
    }//GEN-LAST:event_btnAgregarInvActionPerformed

    private void btnEliminarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInvActionPerformed
        // TODO add your handling code here:
        int fila = tablaVentas.getSelectedRow();
        String valor = tablaVentas.getValueAt(fila, 0).toString();
        System.out.println(valor);
        String condicion = "idVentas="+valor;
        try{
            eliminar("ventas", condicion);
            llenarTabla();
            System.out.println("Metodo");
        }catch(Exception e){
            System.out.println("Chin");
        }
    }//GEN-LAST:event_btnEliminarInvActionPerformed

    private void btnModificarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarInvActionPerformed
        // TODO add your handling code here:}
        int fila = tablaVentas.getSelectedRow();
        int valor = Integer.parseInt(this.tablaVentas.getValueAt(fila, 0).toString());        
        String fecha = tablaVentas.getValueAt(fila, 1).toString();
        float monto = Float.parseFloat(tablaVentas.getValueAt(fila, 2).toString());
        String formaPago = tablaVentas.getValueAt(fila, 3).toString();
        String condicion = "idVentas="+valor;
        String campos = "fecha='"+fecha+"',monto="+monto+",formaPago='"+formaPago+"'";
        try{            
            modificar("ventas", campos, condicion);
            llenarTabla();
        }catch(Exception e){
            System.out.println("Chin");
        }
    }//GEN-LAST:event_btnModificarInvActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Principal prin = new Principal();
        prin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void llenarTabla(){
        try {
      conexion = DriverManager.getConnection(url, usuario, password);

      // 2. Crear statement y ejecutar consulta
      Statement stmt = conexion.createStatement();
      ResultSet rs = stmt.executeQuery("SELECT * FROM ventas");

      // 3. Crear modelo de datos
      DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("ID");
      modelo.addColumn("Fecha");
      modelo.addColumn("Monto");
      modelo.addColumn("FormaPago");

      // 4. Agregar datos al modelo
      while (rs.next()) {
        Object[] fila = new Object[4];
        fila[0] = rs.getInt("idVentas");
        fila[1] = rs.getString("fecha");
        fila[2] = rs.getString("monto");
        fila[3] = rs.getString("formaPago");
        modelo.addRow(fila);
      }

      // 5. Crear JTable y establecer modelo
      tablaVentas.setModel(modelo);

      

      // 7. Cerrar recursos
      rs.close();
      stmt.close();
      conexion.close();

    } catch (SQLException e) {
      e.printStackTrace();
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarInv;
    public javax.swing.JButton btnEliminarInv;
    public javax.swing.JButton btnModificarInv;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboFPago;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    private static String eliminar(java.lang.String nombreTabla, java.lang.String condicion) {
        pkg.webservice.WSTortilleria_Service service = new pkg.webservice.WSTortilleria_Service();
        pkg.webservice.WSTortilleria port = service.getWSTortilleriaPort();
        return port.eliminar(nombreTabla, condicion);
    }

    private static String consultar(java.lang.String nombreTabla, java.lang.String datos, java.lang.String condicion) {
        pkg.webservice.WSTortilleria_Service service = new pkg.webservice.WSTortilleria_Service();
        pkg.webservice.WSTortilleria port = service.getWSTortilleriaPort();
        return port.consultar(nombreTabla, datos, condicion);
    }

    private static String insertar(java.lang.String nombreTabla, java.lang.String campos) {
        pkg.webservice.WSTortilleria_Service service = new pkg.webservice.WSTortilleria_Service();
        pkg.webservice.WSTortilleria port = service.getWSTortilleriaPort();
        return port.insertar(nombreTabla, campos);
    }

    private static String modificar(java.lang.String nombreTabla, java.lang.String campos, java.lang.String condicion) {
        pkg.webservice.WSTortilleria_Service service = new pkg.webservice.WSTortilleria_Service();
        pkg.webservice.WSTortilleria port = service.getWSTortilleriaPort();
        return port.modificar(nombreTabla, campos, condicion);
    }
}

